FROM messense/rust-musl-cross:aarch64-musl as builder

# RUN apt-get update && apt-get install musl-tools

RUN cargo new dotenv-linter
COPY Cargo.toml ./
COPY src ./src
COPY benches ./benches

RUN apt-get update && apt-get install musl-tools -y

RUN cargo build --release --target aarch64-unknown-linux-musl
RUN cargo install --target aarch64-unknown-linux-musl --path .

FROM scratch
COPY --from=builder /root/.cargo/bin/dotenv-linter /
ENTRYPOINT ["/dotenv-linter"]
